all:
	@cd gobject/ && make all
	@cd gtk2/ && make all
	@cd gtk3/ && make all
	@cd cairo/ && make all

.PHONY:clean all

clean:
	@cd gobject/ && make clean
	@cd gtk2/ && make clean
	@cd gtk3/ && make clean
	@cd cairo/ && make clean
