all:
	@cd gobject/ && make all
	@cd gtk2/ && make all
	@cd gtk3/ && make all
	#@cd gdk3/ && make all
	@cd ipc/ && make all
	@cd glib/ && make all
	@cd gio/ && make all
	@cd dbus/ && make all
	@cd cairo/ && make all
	@cd pam/ && make all

.PHONY:clean 

clean:
	@cd gobject/ && make clean
	@cd gtk2/ && make clean
	@cd gtk3/ && make clean
	@cd gdk3/ && make clean
	@cd ipc/ && make clean
	@cd glib/ && make clean
	@cd gio/ && make clean
	@cd dbus/ && make clean
	@cd cairo/ && make clean
	@cd pam/ && make clean
